### ISSUE TITLE
Chat.sendMessageHook definition missing

### ISSUE THREAD

**Issue by thoys** [ManticoreGamesInc/vscode-core#425]
**Describe the bug**
The `Chat.sendMessageHook:Connect` gives an undefined error in the VSCode editor, while it is a valid Core API definition.

**To Reproduce**

N/A

**Expected behavior**
No error

**Screenshots**
![image](https://user-images.githubusercontent.com/607735/131827674-53a45410-eba4-46cb-8b39-302a110ea45b.png)

**Versions:**

- VSCode Version: 1.59.1
- OS Version: Windows 10 19043.1165

**Additional context**

**Comment by StanzillaManticore** [comment]
Thank you, will take a look!
